# Generated by Django 3.1.4 on 2021-02-11 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Partners', '0002_auto_20210211_2243'),
        ('Product', '0003_auto_20210211_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customereviews', to='Partners.customer'),
        ),
    ]
