# Generated by Django 3.1.4 on 2021-02-18 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_auto_20210217_0543'),
        ('Product', '0005_remove_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AddField(
            model_name='review',
            name='OrderItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderReviews', to='Order.orderitem'),
        ),
    ]
