# Generated by Django 3.1.4 on 2021-02-19 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_auto_20210218_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='OrderItem',
        ),
        migrations.AddField(
            model_name='review',
            name='productreviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productreviews', to='Product.product'),
        ),
    ]
