# Generated by Django 3.1.4 on 2021-02-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='supplier',
        ),
    ]
