# Generated by Django 3.1.4 on 2021-02-19 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_auto_20210217_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='rating',
        ),
    ]
